# Generated by Django 3.2.9 on 2021-11-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=128)),
            ],
        ),
    ]
