# Generated by Django 3.2.9 on 2021-11-11 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_breakfast', models.CharField(max_length=200)),
                ('meal_lunch', models.CharField(max_length=200)),
                ('meal_dinner', models.CharField(max_length=200)),
                ('meal_snack', models.CharField(max_length=200)),
                ('meal_dessert', models.CharField(max_length=200)),
                ('meal_drink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfFoods', models.CharField(max_length=300)),
                ('votes', models.IntegerField(default=0)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countit.meals')),
            ],
        ),
    ]
