# Generated by Django 3.2.9 on 2021-11-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countit', '0002_meals_typeoffoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='meal_breakfast',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meal_dessert',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meal_dinner',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meal_drink',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meal_lunch',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meal_snack',
        ),
        migrations.AddField(
            model_name='meals',
            name='calory',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='type_of_food',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='type_of_meals',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='TypeOfFoods',
        ),
    ]
