# Generated by Django 3.2.9 on 2021-11-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countit', '0003_auto_20211111_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meals',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='calory',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
