# Generated by Django 3.2.9 on 2021-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countit', '0004_auto_20211111_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='calory',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='calories',
            field=models.FloatField(null=True),
        ),
    ]
